apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      role: msvc-gateway
  template:
    metadata:
      labels:
        role: msvc-gateway
    spec:
      containers:
        - name: msvc-gateway
          image: gfernandez16/gateway:latest
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-gateway
spec:
  ports:
    - protocol: TCP
      #puerto del servicio, del loadbalancer
      port: 8090
      #puerto de la aplicacion que esta dentro del contenedor.
      targetPort: 8090
  #va seleccionar todos los pods que tengas esa etiqueta
  selector:
    role: msvc-gateway
  type: LoadBalancer