apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-usuarios
spec:
  replicas: 3
  #Para seleccionar los pods para este deployment
  selector:
    matchLabels:
      app: msvc-usuarios
  template:
    metadata:
      labels:
        app: msvc-usuarios
    spec:
      containers:
      #..:latest, hara que siempre descargue la ultima version latest de dockerhub la imagen,
      #si se pone una version v2, y ya existe una imagen en v2 en kubernetes, no lo va descargar
      - image: gfernandez16/usuarios:latest
        name: usuarios
        ports:
        - containerPort: 8001
