version: "3.9"
services:
  mysql8:
    container_name: mysql8
    #esta imagen si no la tenemos creada en nuestra maquina, lo puede bajar automaticamente de docker-up. Al igual que postgres
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      #MYSQL_ROOT_PASSWORD: mysqldb
      #MYSQL_DATABASE: msvc_usuarios
      - MYSQL_ROOT_PASSWORD=mysqldb
      - MYSQL_DATABASE=msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
    image: gfernandez16/usuarios:latest
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: mysqldb
      CURSOS_URL: ec2-54-90-126-41.compute-1.amazonaws.com:8002
    networks:
      - spring
    depends_on:
      - mysql8
    #un restart, si cuando inicie este contenedor aun no esta totalmente levantado el contenedor del mysql
    restart: always

volumes:
  data-mysql:
    #si no colocamos ningun atributo al data-mysql, va crear un nombre de volume por defecto(curso-kubernetes_data-mysql)
    name: data-mysql

networks:
  spring:
    name: spring