apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    #capacidad maxima de almacenamiento, se mide en gigas
    storage: 2Gi
  #Es la clase de almacenamiento que tenemos actualmente, ahora en el curso con minikube nos muestra 'standard'
  storageClassName: standard
  #por defecto suele ser este modo, este atributo es opcional
  volumeMode: Filesystem
  #tipos de acceso que se van a poder solicitr con los 'VolumeClaim' desde los deployments
  accessModes:
    #Once, significa un solo nodo, como lo que se tiene con minikube
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/data
    type: DirectoryOrCreate