apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  volumeName: postgres-pv
  accessModes:
    #recomendable que coincida con lo definido en mysql-pv
    ##- ReadWriteOnce
    - ReadWriteMany
  #storageClassName: standard
  storageClassName: ""
  #Aca de define la capacidad de almacenamiento que se necesitara. No debe superar lo definico en pv.yaml
  resources:
    requests:
      storage: 2Gi