apiVersion: v1
kind: Service
metadata:
  name: msvc-usuarios
spec:
  ports:
  #nodePort, no es necesario lo podria manejar de forma automatica, seria necesario cuando el tipo(type) en vez
  # de LoadBalancer fuera NodePort, ahora se podria quitar porque al ser LoadBalancer lo podria manejar automaticamente
##  - nodePort: 31032
    #este es el puerto del servicio para manejar el trafico
    - port: 8001
      protocol: TCP
    #puerto de la aplicacion que esta dentro del contenedor, de msvc-usuarios
      targetPort: 8001
  #va seleccionar todos los pods que tengas esa etiqueta
  selector:
    app: msvc-usuarios
  type: LoadBalancer
